---
- name: Make sure the import directory exists
  tempfile:
    prefix: "gpg-import"
    state: directory
  register: gpg_import_directory

- name: Copy gpg keys
  copy:
    content: "{{ item.src }}"
    dest: "{{ gpg_import_directory.path }}/{{ item.name }}"
    mode:  0600
  no_log: true
  with_items:
    - name: "private.key"
      src: "{{ gpg_private_key }}"

- name: Import private key
  command: "gpg --allow-secret-key-import --batch --passphrase=\"{{ gpg_private_key_passphrase }}\" --import {{ gpg_import_directory.path }}/private.key"
  register: gpg_private_key_import_status
  ignore_errors: true
